### ISSUE TITLE
Broken while parse ((name eq 'Drew Xiu') and (age gt 5))

### ISSUE THREAD

**Issue by noru** [jadrake75/odata-filter-parser#12]
```json
{
  "key": "INVALID_FILTER_STRING",
  "msg": "The given string has uneven number of parenthesis"
}
```

Error gone when the space between the first string removed or set 5 to 10 (non-single-digit number).

**Comment by jadrake75** [comment]
@noru this is now fixed with version v0.5.0 - the test is in a later commit since I didn't see it until after submission
