### ISSUE TITLE
Incorrect parsing if function has space after comma

### ISSUE THREAD

**Issue by KimDal-hyeong** [jadrake75/odata-filter-parser#13]
Parse `contains(name, 'Something') and (name eq 'test')`

expect:
```js
{
  subject: Predicate { subject: 'name', value: '*Something*', operator: 'like' },
  value: Predicate { subject: 'name', value: 'test', operator: 'eq' },
  operator: 'and'
}
```

result:
```js
{
  subject: null,
  value: Predicate { subject: 'name', value: 'test', operator: 'eq' },
  operator: 'and'
}
```

**Comment by jadrake75** [comment]
Thanks @KimDal-hyeong.  I was able to handle this with a minor REGEX update to account for spaces within the functions supported.  Wasn't sure if this was working for you before and broke with the recent v0.5.0 update or if this was a new case, but it was easy enough to fix and commit.

**Comment by jadrake75** [comment]
v0.5.2+ will work with this use case
