### ISSUE TITLE
Is null operator support

### ISSUE THREAD

**Issue by dancundy** [jadrake75/odata-filter-parser#14]
Maybe I'm missing something but how is "is null" supported? I see it in the list of supported [OData operators](https://github.com/jadrake75/odata-filter-parser/blob/master/doc/Intro.md#operators) in the documentation.

I've tried

```
var p = new odataFilter.Predicate({
	subject: 'name',
	operator: 'is null',		
})
var s = p.serialize()

// output: "(name is null)"
```

But If I try and parse that OData filter, null is always returned.

```
const predicate: Predicate = odataFilter.Parser.parse('name is null')

// output: null
```

I've also tried

```
var p = new odataFilter.Predicate({
	subject: 'name',
	operator: 'eq',		
        value: null
})
var s = p.serialize()

// output: runtime error
```

If I try and parse that filter, 0 is always returned as the value. 

```
const predicate: Predicate = odataFilter.Parser.parse('name eq null')

// output:
// {
//	operator: "eq",
//	subject: "name",
//	value: 0,
// }
```

**Comment by jadrake75** [comment]
@dancundy I missed this issue (need to check my notifications).  so I wrote a quick test and I agree it is not handled.  Seemed I added the operator to "build" query predicates, but never actually implemented it for the parse.  I will accept this issue and provide a fix for this.

**Comment by jadrake75** [comment]
I pushed a new version v0.5.4 which has parser support for the is null.  So if you were to call something like

`Parser.parse("name is null")`

It would return a `Predicate` which will have an operator of `is null` and a subject of `name`.  The value would be empty/undefined

**Comment by dancundy** [comment]
@jadrake75 Thank you for the quick turnaround!
