### ISSUE TITLE
Version published to npm does not match git tag

### ISSUE THREAD

**Issue by Nulifier** [jadrake75/odata-filter-parser#19]
The version 0.5.4 which is published on npm does not match the code in this git repository for that tag. Specifically [here in GitHub](https://github.com/jadrake75/odata-filter-parser/blob/163470ccf6b8cce016e50dc0369a3859129437dd/src/odata-parser.js#L210) compared with [npm](https://www.npmjs.com/package/odata-filter-parser/v/0.5.4?activeTab=code).

This prevents the 'is null' function from working.

**Comment by jadrake75** [comment]
I released a new version v0.5.5 and created a version in github which appears to have both the same binaries
