### ISSUE TITLE
Plunker Demo?

### ISSUE THREAD

**Issue by kjartanvalur** [jadrake75/odata-filter-parser#7]
Hi

I´m having problem using this library.. Can you maybe make a simple Plunker demo?

http://plnkr.co/edit/OtJ0xz2K2E1EWQx4cEv4?p=preview

**Comment by jadrake75** [comment]
I will try and get to this later tonight.  Can you describe what you are hoping to do?  Might help my focus the demo situation a little.

**Comment by kjartanvalur** [comment]
@jadrake75 
Thanks! I´m trying to parse a $filter string to an structured object. Hoping this function would do the trick... parse(filter:string)

**Comment by jadrake75** [comment]
http://plnkr.co/edit/1ty8AlJyJ2Kyd25dTfO6?p=preview
