### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by kjartanvalur** [jadrake75/odata-filter-parser#8]
Hi

Can someone explain why this is not working?

http://plnkr.co/edit/DuN1oE5E6q8s7pdpfrGT?p=preview
```

console.log(ODataParser.parse("name eq test"));
//returns value: 0
console.log(ODataParser.parse("name startswith test"));
//returns null
console.log(ODataParser.parse("name endswith test"));
//returns null
console.log(ODataParser.parse("name contains test"));
//returns null
console.log(ODataParser.parse("name doesnotcontain test"));
//returns null
```

**Comment by jadrake75** [comment]
http://plnkr.co/edit/1ty8AlJyJ2Kyd25dTfO6?p=preview

the doesnotcontain is not supported at the moment.  not sure where you got that

see http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part2-url-conventions.html
5.1.1.5.2 contains
5.1.1.5.6. startswith
5.1.1.5.3. endswith

you need to encode the strings with '' and the contains/startsWith and endswith are functions in ODATA
